### ISSUE TITLE
How to use with a test suite?

### ISSUE THREAD

**Issue by bmulholland** [codedbychavez/configcat-vue#16]
We need to write unit & e2e tests that cover both states of the feature flipper. How do we do that? Can we just follow [these instructions](https://configcat.com/docs/sdk-reference/js/#flag-overrides) and the overrides will apply to the Vue component's state? Is there another way to force the value to be something? Would need to be at runtime, e.g. in the browser, I think.

**Comment by adams85** [comment]
> Can we just follow [these instructions](https://configcat.com/docs/sdk-reference/js/#flag-overrides) and the overrides will apply to the Vue component's state?

Yep, I think this is the simplest approach. Flag overrides should work with the Vue plugin just fine.

> Is there another way to force the value to be something?

Alternatively, providing a mock for `IConfigCatClient` could work as well, since it's [injected as a dependency](https://github.com/codedbychavez/configcat-vue/blob/89fde34dd73f624ca9a53961b38d9ebe13ca9f4b/src/components/FeatureWrapper.vue#L34). You'd need to provide some fake implementation of `IConfigCatClient.snaphot()`, plus of `IConfigCatClient.on("configChanged", ...)` if you want to test state transitions.

**Comment by adams85** [comment]
FYI, we've added some tests recently, so now we have some examples of how to apply those mocking techniques I talked about in my previous comment: https://github.com/codedbychavez/configcat-vue/blob/main/tests/unit/FeatureWrapper.spec.ts

**Comment by codedbychavez** [comment]
Closing...
